/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type MeasurementType = "distance" | "duration" | "reps";

export type Numeric = ColumnType<string, number | string, number | string>;

export type SessionStatus = "completed" | "in_progress" | "planned" | "skipped";

export type SetStatus = "auto_skipped" | "completed" | "skipped";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Exercise {
  categoryId: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  importantNote: string | null;
  level: Numeric;
  measurementType: MeasurementType;
  name: string;
  targetNote: string | null;
  targetToUnlockNext: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface ExerciseCategory {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Program {
  createdAt: Generated<Timestamp>;
  defaultRestBetweenExercises: Generated<number>;
  defaultRestBetweenRounds: Generated<number>;
  defaultRounds: Generated<number>;
  id: Generated<string>;
  name: string;
  trainingDays: number[];
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface ProgramExercise {
  categoryId: string;
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  id: Generated<string>;
  programId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpiresAt: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface UserExerciseProgression {
  baseValue: Generated<number>;
  categoryId: string;
  createdAt: Generated<Timestamp>;
  exerciseId: string;
  id: Generated<string>;
  initialBaseValue: Generated<number>;
  unlockedAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface WorkoutSession {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  plannedRestBetweenExercises: number;
  plannedRestBetweenRounds: number;
  plannedRounds: number;
  programId: string;
  roundsCompleted: number | null;
  scheduledDate: Timestamp | null;
  startedAt: Timestamp | null;
  status: Generated<SessionStatus>;
  totalActiveSeconds: number | null;
  totalDurationSeconds: number | null;
  totalRestSeconds: number | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface WorkoutSessionExercise {
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  exerciseId: string;
  id: Generated<string>;
  skipped: Generated<boolean>;
  targetValue: Generated<number>;
  updatedAt: Generated<Timestamp>;
  workoutSessionId: string;
}

export interface WorkoutSet {
  actualValue: number | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  durationSeconds: number | null;
  id: Generated<string>;
  restAfterSeconds: number | null;
  roundNumber: number;
  sessionExerciseId: string;
  startedAt: Timestamp | null;
  status: Generated<SetStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  account: Account;
  exercise: Exercise;
  exerciseCategory: ExerciseCategory;
  program: Program;
  programExercise: ProgramExercise;
  session: Session;
  user: User;
  userExerciseProgression: UserExerciseProgression;
  verification: Verification;
  workoutSession: WorkoutSession;
  workoutSessionExercise: WorkoutSessionExercise;
  workoutSet: WorkoutSet;
}
